name: "Flask app on GitHub"

run-name: "Flask CI/CD Pipeline"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # Allow to manually check_run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run basic test
        run: python - "import flask"

      - name: Build Docker image
        run: |
          docker build -t flask-docker-app .

  docker-push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/flask-docker-app:latest .
          docker push ${{ vars.DOCKER_USERNAME }}/flask-docker-app:latest